### PR TITLE
Improvements to the tracer.

### PR DESCRIPTION
**Pull request by veelo**
1. Improved position indication.
2. Extended support for trace conditions.

### CODE REVIEW

**Comment by PhilippeSigaud** [comment]
I merged it, and #220 also.

What about a small version bump? Do you have any other improvements in mind?

**Comment by veelo** [comment]
Thanks!

> What about a small version bump? Do you have any other improvements in mind?

Hold on a moment, I'd like to propose a longest_match parser. Coming up!

**Comment by veelo** [comment]
I'm ready for a version bump. https://github.com/PhilippeSigaud/Pegged/wiki/Extended-PEG-Syntax#longest-match-alternation

Also, I found it was about time to document the left-recursion algorithm, before I forget: https://github.com/PhilippeSigaud/Pegged/wiki/Left-Recursion

The tracer and HTML output are still undocumented I believe, but that'll have to wait. 

Thanks.

**Comment by PhilippeSigaud** [comment]
The left-recursion documentation is very well written very interesting to read.

I'll bump the version to v0.4.0. Between the new documentation for left-recursion and the longest-match rule, field-tested on the EP grammar, that's quite justified.

**Comment by veelo** [comment]
Nice! Thanks.

**Comment by PhilippeSigaud** [comment]
There, that's done. See:

https://github.com/PhilippeSigaud/Pegged/releases

Tell me if I have to add something in the release notes.

**Comment by veelo** [comment]
No it looks really nice. Thanks for the creds. Are you planning on leaving a note on the announce news group?

**Comment by PhilippeSigaud** [comment]
Yeah, good idea, I should do that. I've to go to work right now, I'll do
that in a few hours.

**Comment by veelo** [comment]
> The tracer and HTML output are still undocumented I believe, but that'll have to wait.

I found that I did document the tracer. Just updated it to the changed `traceCondition` API:
https://github.com/PhilippeSigaud/Pegged/wiki/Grammar-Debugging

**Comment by veelo** [comment]
And I added a short mention of `toHTML` in https://github.com/PhilippeSigaud/Pegged/wiki/Using-the-Parse-Tree.

**Comment by veelo** [comment]
Turns out `toHTML` was already documented here https://github.com/PhilippeSigaud/Pegged/wiki/Parse-Result

Too bad the Wiki has no search function.

I'll shut up now :-)

**Comment by PhilippeSigaud** [comment]
There, here is the Announce post:

https://forum.dlang.org/post/qhcbtyvxlrabiqnccceo@forum.dlang.org

**Comment by veelo** [comment]
Thank you. It's a nice announcement.

**Pull request merged**
