### PR TITLE
Add generated HTML, for inclusion in the Wiki through rawgit.com.

### PR DESCRIPTION
**Pull request by veelo**
Not sure this'll work, it'd be nice.

### CODE REVIEW

**Comment by PhilippeSigaud** [comment]
I merged it, but I don't think it worked.

**Comment by veelo** [comment]
It does work now. Link at the very bottom of https://github.com/PhilippeSigaud/Pegged/wiki/Parse-Result.

:-)

**Comment by PhilippeSigaud** [comment]
Oh, nice! It's fun to play with the tree in that way!

**Comment by PhilippeSigaud** [comment]
So, I wasn't aware you could generate this HTML5 tree. Maybe I should give
some info in the release notes?

**Comment by veelo** [comment]
Yes it's very nice to have this example online now, being able to play with it right there is worth much more than a few lines of documentation. Glad you like it. Finding the rule that failed is also much more fun this way. Maybe we need an example of that as well ;-)

A bit of publication in the release notes can do no harm, indeed.

**Comment by PhilippeSigaud** [comment]
Hmm, since the wiki example was added after the v0.4.0 tag (and I do not
know how to move a tag to master), I created a patch release 0.4.1.

**Pull request merged**
