### PR TITLE
Improve readability of failure messages.

### PR DESCRIPTION
**Pull request by veelo**
Is this enough to close PhilippeSigaud/Pegged#183?

### CODE REVIEW

**Comment by Temtaime** [comment]
I have a better implementation to stringified.
return format(`%(%s%s)`, (&inp)[0..1]);

**Comment by veelo** [comment]
> `return format("%(%s%s)", (&inp)[0..1]);`

@Temtaime This looks smart, but it's too smart for me. Can you explain why this would work, and why it is better? And shouldn't the closing brace in the format string be `%)`?

Thanks!

**Comment by Temtaime** [comment]
Yes, my mistake missed %.
http://dpaste.dzfl.pl/75bb43c8db64
It replaces all the special characters, so there's no need in making custom tables, so i think it's reliablier and better, also it's less code.
Main idea is output an array of strings but with only one string. (&inp)[0..1] makes a slice with our string.

**Comment by veelo** [comment]
OK so it traverses the string one character at a time and formats special characters? I agree that it would be more reliable. But I notice that the \r is replaced by \n in your dpaste. I don't think this is what we want. What is your opinion?

**Comment by Temtaime** [comment]
Oh, see it too. It's strange, i think it's phobos bug, going to post to bugzilla and make a pr.
But i think it's ok to use format, it also takes care about non-printable characters.

**Comment by veelo** [comment]
Thanks. Maybe it is platform-dependent. Can you add a link to bugzilla here?

**Comment by Temtaime** [comment]
Hmmm, i've cheched on both windows and linux, and all is ok. Maybe it's a problem with dpaste ?
Will ask on dlang.org

**Comment by veelo** [comment]
It's OK on Mac too, dmd64 v2.070.0.

**Comment by PhilippeSigaud** [comment]
In that case, I'll merge that.
Thanks to you both!

**Pull request merged**
