### PR TITLE
Normalize indentation and trailing spaces

### PR DESCRIPTION
**Pull request by Zardoz89**
This should finish issue #277 

Also, I modernizes/cleans the gitignore file and tweaked the .editorconfig to control YAML and BAT files.

### CODE REVIEW

**Comment by veelo** [comment]
Travis CI shows that it hasn't completed yet on github, but on Travis it seems to have passed. There is a mention about "sudo key deprecated", you might want to look into that on https://travis-ci.com/github/PhilippeSigaud/Pegged/builds/158782714/config#rccb_Pegged:.travis.yml@cf6cc46ac901814b.2.

I'm merging this, thanks for the touch up.

**Comment by Zardoz89** [comment]
I see. The sudo isn't doing anything, but doesn't break anything. I would change it.

@veelo On where I could help more with Pegged ? I can't help much more on the windows side (I don't have a Windows dev enviroment), but I can keep pushing stuff with Linux. Helping here it's becoming one of my main pastimes with the confinement. :P

**Comment by veelo** [comment]
> @veelo On where I could help more with Pegged ? I can't help much more on the windows side (I don't have a Windows dev enviroment), but I can keep pushing stuff with Linux. Helping here it's becoming one of my main pastimes with the confinement. :P

That is great to hear! I am currently working with Philippe to create a GitHub organization for Pegged, so that responsibility for maintaining Pegged can be shared among several people. You're welcome to be part of that team if you want to.

There are several ideas floating around, but they potentially require a lot of work:

* Traversing a parse tree requires big switches on strings. Supporting switches on enums can potentially speed up traversal and adds the advantage of `final switch`. See #156. You may also want to have a look at the implementation of dscanner for reference.
* Code cleanup. See the discussion in #190 and #175 and #134.
* I once looked into optimizing memoization, without much luck. Maybe a second set of eyes will help. #176.
* Improve examples. #161, #55.

There may be other issues that can give you inspiration.

Have fun!

**Comment by Zardoz89** [comment]
On the lines of #55,  I have toying with executing the examples unit-tests (that should be improved) and sharing it as a dub subpackages, instead of including all on a monolithic dub package. I would continue it and try to update/fix and improve the examples.

**Pull request merged**
