### PR TITLE
add support for debian packaging

### PR DESCRIPTION
**Pull request by ikod**
This pull request adds support for building debian package from Pegged sources. 
The goal is to have a package which can install Pegged source files and static library in system-wide directories: sources to /usr/include/d/, library to /usr/lib/. After package installed you can both compile your code and run rdmd scripts with shebang line like
```
#!/usr/bin/rdmd --shebang -I/usr/include/d -L-lpegged
```
Requirements to build package: Debian system starting from "Squeeze", packages _dpkg-dev,debhelper_, D compiler packages: _dmd_ version started from 2.069.2, _gdc_ version starting from 4.9.2-2

Steps to build package:

1. Use Debian system starting from "squeeze" (tested on "squeeze" and "jessie"), 
2. install packages: dpkg-dev,  debhelper, D-compiler (dmd or gdc):
 * apt-get install dpkg-dev debhelper gdc
3. clone project from github and run builder in the Pegged directory:
 * cd Pegged && dpkg-buildpackage -b
4. You will find ready package _dlang-pegged_ in file with name like dlang-pegged_0.3.1-1_amd64.deb in parent directory

### CODE REVIEW

**Comment by veelo** [comment]
Hi,

It seems many of the files are stubs, ready to be customised (or deleted). I don't think all files should be merged in the state they are in.

What are further plans, is your intention to get this accepted by Debian, or will you serve this as a 3rd party? If it is the first, there are many blanks that need to be filled in to comply with the Debian standards...

Thanks for making a good start though.

**Comment by ikod** [comment]
I can remove all these .ex files, but they can be used for fast further customization. Never thinking of submitting this to Debian, but this is good point to go furthed dlang packages in Debian.

My proposal: to clean all unneeded files, fill any fields I missed (@veelo, please help to find)  and see where we can move from this point.

**Comment by veelo** [comment]
OK. I'd remove everything that doesn't contribute any information. The files can always be found in the history when needed. Would be strange if the packaging had more files than the library.

In addition to `*.ex`, the `README.*` files should be filled or removed. `Changelog` cleaned. What is `compat` for? `control` can use a line break or two. `copyright` contains stubs. Does `rules` and `format` do anything?

**Comment by ikod** [comment]
- *.ex files removed
- changelog cleaned
- control file have more or less strict format, it was generated by debian developer helper system, I just changed some fields.
- compat and rules are part of building system.
- copyright filled with info, available to me.
- format removed.

Here is link to debian packaging policy: https://www.debian.org/doc/debian-policy/ for details.

**Comment by veelo** [comment]
Much better now. Is the `makefile` needed in `debian/`, or can it be unified with the `makefile` in the root directory?

**Comment by ikod** [comment]
sorry, but I can't find makefile in debian directory. Here is complete list of "debian":
changelog
compat
control
copyright
install
rules

Anyway any makefile not needed in this directory

**Comment by veelo** [comment]
> sorry, but I can't find makefile in debian directory.

O I'm sorry I misread. Looks good to me now!

Bastiaan.

**Comment by PhilippeSigaud** [comment]
Thanks a lot @ikod, for your work!

**Comment by ikod** [comment]
Thank you, Philippe both for merging PR and for Pegged :)

**Pull request merged**
