### PR TITLE
Provide a custom file logger that gets rid of the time stamps.

### PR DESCRIPTION
**Pull request by veelo**

### CODE REVIEW

**Comment by veelo** [comment]
I just wrote https://github.com/PhilippeSigaud/Pegged/wiki/Grammar-Debugging in anticipation of the pulling of this PR.

**Comment by PhilippeSigaud** [comment]
On Sun, Feb 28, 2016 at 1:21 AM, Bastiaan Veelo <notifications@github.com>
wrote:

> I just wrote
> https://github.com/PhilippeSigaud/Pegged/wiki/Grammar-Debugging in
> anticipation of the pulling of this PR.
>

Very good, I'll merge this PR. I see on the wiki page that internal peg
parsers are traced as well. IIRC, there was a way to get tracing only on
the user-defined rules, or am I misremembering?

**Comment by veelo** [comment]
> IIRC, there was a way to get tracing only on the user-defined rules, or am I misremembering?

It is in the next sentence :-)

**Comment by PhilippeSigaud** [comment]
Drat, sorry. In my defense, I had a severe flu yesterday. I asked the
question while reading the very last paragraph and apparently forgot I read
the answer one minute earlier :-)

**Pull request merged**
