### PR TITLE
[refactor] Add a default value to 'parseArithmetic' in the arithmetic example grammar

### PR DESCRIPTION
**Pull request by iK4tsu**
By adding a default value, there's no longer the need to have an overloaded function. Since the function never modifies the original AA, there's no need for it to be passed by reference either.

### CODE REVIEW

**Comment by veelo** [comment]
Thanks a lot!

**Comment by iK4tsu** [comment]
Not really, can be whatever you prefer. Thank you! :smile:

**Comment by ljmf00-wekaio** [comment]
> > @veelo btw could you add the `hacktoberfest-accepted` label?
> 
> I'll have to create one. Do you have a preferred color?

You can add `hacktoberfest` tag on the repo, so you don't need to add this label on every PR :)

**Comment by veelo** [comment]
> You can add `hacktoberfest` tag on the repo, so you don't need to add this label on every PR :)

I have looked for that option, but I'm just a maintainer, and I think you have to be owner for that.

**Pull request merged**
